# Generated by Django 3.0.5 on 2020-04-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=300)),
                ('mix', models.IntegerField(max_length=5)),
                ('match', models.IntegerField(max_length=5)),
            ],
        ),
    ]
