# Generated by Django 2.2.12 on 2020-04-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoApps', '0002_auto_20200418_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix', models.CharField(max_length=30)),
                ('match', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('idea', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
